name: anniversary
description: An app to keep track of that special day.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_redux: ^0.5.0
  shared_preferences: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
      - family: Bitter
        fonts:
          - asset: fonts/Bitter-Regular.ttf
          - asset: fonts/Bitter-Bold.ttf
            weight: 700
          - asset: fonts/Bitter-Italic.ttf
            style: italic
